name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  auto-merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Wait for CI to complete
      uses: fountainhead/action-wait-for-check@v1.1.0
      id: wait-for-ci
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: 'Test'
        ref: ${{ github.event.pull_request.head.sha }}
        timeoutSeconds: 1800
        intervalSeconds: 30
        
    - name: Auto-merge patch and minor updates
      if: steps.wait-for-ci.outputs.conclusion == 'success'
      uses: pascalgn/merge-action@v0.15.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        merge_method: squash
        merge_commit_message: automatic
        merge_filter_author: dependabot[bot]
        merge_forks: false
        merge_labels: "dependencies"
        merge_remove_labels: ""
        merge_delete_branch: true
